/* Leetcode 389. Find the Difference

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
*/

class Solution {
    public char findTheDifference(String s, String t) { 
        //HashSet did not allowed have same element
        HashSet<Character> set = new HashSet<>(); 
        
        //Traverse all the character from String s and t and try to add into hashset
        for(char c : (s+t).toCharArray()){
            if(!(set.add(c))){ //if can not add it, it means hashset have same character
                set.remove(c); // remove it
            } else{
                set.add(c); //if success add it, means not have same character in the HashSet
            }
        }
        
        return set.iterator().next(); // return the character from HashSet
    }
}
